#!/bin/bash

git submodule add https://github.com/Shougo/neobundle.vim .vim/bundle/neobundle.vim || :
ln -sf $PWD/.vimrc ~/.vimrc
ln -sf $PWD/.vim ~/.vim
ln -sf $PWD/.gitconfig ~/.gitconfig
ln -sf $PWD/.tmux.conf ~/.tmux.conf
