#!/bin/bash

git clone git://github.com/Shougo/neobundle.vim ~/.vim/bundle/neobundle.vim || :
ln -sf $PWD/.vimrc ~/.vimrc
ln -sf $PWD/.vim ~/.vim
ln -sf $PWD/.gitconfig ~/.gitconfig
ln -sf $PWD/.tmux.conf ~/.tmux.conf
cd ~
echo | vim +NeoBundleInstall +qall
